// levels.js — GENERATED by generate.js (seed 20260908). Do not hand-edit.
// Every level below was proven solvable (death-free) by the BFS solver; `par` is
// its shortest solution. Legend: #wall .ice =sand x=pit @player $block o target
// (A/B/T = player/block/target on sand). A block shoved into a pit fills it.
(function (root) {
  const LEVELS = [
  { name: "1. Drift", par: 4, map: "########\n#.$...o#\n#=.....#\n#=...@=#\n#......#\n#.....=#\n#......#\n########" },
  { name: "2. Brakes", par: 11, map: "########\n#.....o#\n#....=.#\n##...o.#\n#=...$.#\n#@...$.#\n#=..#..#\n########" },
  { name: "3. Sandbar", par: 17, map: "########\n#...#..#\n#==....#\n#o.$...#\n#.@=..=#\n#......#\n#......#\n########" },
  { name: "4. Detour", par: 24, map: "########\n##....o#\n#=.....#\n#..$..=#\n#.#...$#\n#...@..#\n#.....o#\n########" },
  { name: "5. Sinkhole", par: 5, map: "########\n#....==#\n#.....@#\n##.....#\n#x$..=.#\n#$....=#\n#o.....#\n########" },
  { name: "6. Threshold", par: 7, map: "########\n#.....=#\n#......#\n#..$=o.#\n##...xx#\n#@....$#\n#......#\n########" },
  { name: "7. Crossing", par: 7, map: "########\n#....o##\n#.x$.@=#\n#..=.#.#\n#......#\n#.=.$..#\n#...=..#\n########" },
  { name: "8. Pitfall", par: 10, map: "########\n#......#\n#.x#=..#\n#...$=.#\n#.=....#\n#..=.$x#\n#o.@...#\n########" },
  { name: "9. Switchback", par: 11, map: "########\n##.....#\n#o...@.#\n#.$....#\n#......#\n#.=...=#\n#x..$=.#\n########" },
  { name: "10. Chasm", par: 11, map: "########\n#@....o#\n#...=..#\n#..=#.x#\n#.==.$.#\n#..#..$#\n#...=..#\n########" },
  { name: "11. Whiteout", par: 13, map: "########\n#.....=#\n#$$...=#\n#......#\n#x...=##\n#@.....#\n#o=..#.#\n########" },
  { name: "12. Abyss", par: 13, map: "########\n#.=.=..#\n#.$=..x#\n#......#\n#......#\n#=$x.@o#\n#.#...=#\n########" },
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = { LEVELS };
  else root.LEVELDATA = { LEVELS };
})(typeof self !== 'undefined' ? self : this);
