// index.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Re-exports every imported entity. Adding an entity is an entry in tools/sprite-manifest.ts and a
// re-run of the importer; nothing here is written by hand.
export { TEMPLATE_PALETTE } from './palette';
export * from './player';
