// palette.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// The TEMPLATE palette: every distinct colour across every imported animation of every entity, in
// first-seen order. A sprite pixel stores an index into this (0 = transparent, n = entry n - 1), so
// this table is the one place a colour code means something — which is what makes a skin or a
// material authored once work identically in every animation, and across entities.
//
// These are CODE colours, not finished art: the source packs are colour-coded templates. Everything
// the player sees is decided in ../skin.ts.
export const TEMPLATE_PALETTE = [
  '#ce5050',
  '#ac3232',
  '#962d2d',
  '#951799',
  '#af1ab2',
  '#df7126',
  '#b35b20',
  '#d1cc60',
  '#fbf236',
  '#6abe30',
  '#99e550',
  '#5fcde4',
  '#c46423',
  '#6e8b99',
  '#9c304d',
  '#76428a',
  '#674085',
  '#69ad31',
  '#5fb4d9',
  '#d95763',
  '#ffffff',
] as const;
