// palette.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// The reference pack's TEMPLATE palette: every distinct colour across every imported animation, in
// first-seen order. A sprite pixel stores an index into this (0 = transparent, n = entry n - 1), so
// this table is the one place a colour code means something — which is what makes an equipment
// override work identically in every animation.
//
// These are CODE colours, not finished art: the pack is a colour-coded template. Shipping art means
// mapping them to DELVE's palette — see ../skin.ts.
export const TEMPLATE_PALETTE = [
  '#ce5050',
  '#ac3232',
  '#962d2d',
  '#951799',
  '#af1ab2',
  '#df7126',
  '#b35b20',
  '#d1cc60',
  '#fbf236',
  '#6abe30',
  '#99e550',
  '#5fcde4',
  '#c46423',
  '#6e8b99',
  '#9c304d',
  '#76428a',
  '#674085',
  '#69ad31',
  '#5fb4d9',
  '#d95763',
  '#ffffff',
] as const;
