// index.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Every player animation listed in tools/sprite-manifest.ts. The source animations
// deliberately NOT imported, and why, are recorded there too.
import { PLAYER_IDLE } from './player-idle';
import { PLAYER_WALK } from './player-walk';
import { PLAYER_RUN } from './player-run';
import { PLAYER_JUMP } from './player-jump';
import { PLAYER_LAND } from './player-land';
import { PLAYER_CROUCH_IDLE } from './player-crouch-idle';
import { PLAYER_CROUCH_WALK } from './player-crouch-walk';
import { PLAYER_ROLL } from './player-roll';
import { PLAYER_HURT } from './player-hurt';
import { PLAYER_DEATH } from './player-death';
import { PLAYER_PUSH } from './player-push';
import { PLAYER_PULL } from './player-pull';
import { PLAYER_PUSH_IDLE } from './player-push-idle';
import { PLAYER_LEDGE_CLIMB } from './player-ledge-climb';
import { PLAYER_AIR_SPIN } from './player-air-spin';

export const PLAYER_SPRITES = {
  idle: PLAYER_IDLE,
  walk: PLAYER_WALK,
  run: PLAYER_RUN,
  jump: PLAYER_JUMP,
  land: PLAYER_LAND,
  crouch_idle: PLAYER_CROUCH_IDLE,
  crouch_walk: PLAYER_CROUCH_WALK,
  roll: PLAYER_ROLL,
  hurt: PLAYER_HURT,
  death: PLAYER_DEATH,
  push: PLAYER_PUSH,
  pull: PLAYER_PULL,
  push_idle: PLAYER_PUSH_IDLE,
  ledge_climb: PLAYER_LEDGE_CLIMB,
  air_spin: PLAYER_AIR_SPIN,
} as const;

export type PlayerAnim = keyof typeof PLAYER_SPRITES;

/**
 * The layer slots a player animation may use, in paint order.
 *
 * Normalised at import precisely so a skin or material authored once applies to every animation —
 * the source pack calls the same body part by several different names across its files.
 */
export const PLAYER_SLOTS = [
  'arm.far',
  'leg.far',
  'torso',
  'leg.near',
  'arm.near',
  'head',
  'weapon',
  'fx.damage',
] as const;

export type PlayerSlot = (typeof PLAYER_SLOTS)[number];
