// player-ledge-climb.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: 2D-Pixel-Art-Character-Template/Ledge Grab-Climb/player ledge climb 48x48.aseprite (5 frames, 48x48)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const PLAYER_LEDGE_CLIMB: SpriteAnim = {
  name: 'player-ledge-climb',
  w: 48,
  h: 48,
  frames: 5,
  ground: 40,
  durations: [120, 120, 120, 120, 120],
  layers: [
    {
      name: 'arm.far',
      cels: [
        { x: 26, y: 11, w: 3, h: 3, data: 'AAQEBAQAAAQA' },
        null,
        null,
        null,
        { x: 18, y: 23, w: 5, h: 4, data: 'AAAEBAQABAQAAAQEAAAABAAAAAA=' },
      ],
    },
    {
      name: 'leg.far',
      cels: [
        {
          x: 13,
          y: 31,
          w: 9,
          h: 7,
          data: 'AAAAAAAAFAAAAAAAABQUFBQAAAAAFBQUFBQUAAICFBQUFBQAAgICFBQUAAAAAgIAAAAAAAAAAgAAAAAAAAAA',
        },
        { x: 22, y: 33, w: 4, h: 9, data: 'AAAUAAAAFBQAABQUABQUFAACFBQCAgIAAgICAAACAgAAAAIC' },
        {
          x: 21,
          y: 30,
          w: 8,
          h: 10,
          data: 'AAAAFAAAAAAAABQUAAAAABQUFBQAAAAAABQUFBQAAAAAABQUFAAAAAAAABQUFAAAAAAAAgICAAAAAAAAAgICAAAAAAACAgIAAAAAAAACAgI=',
        },
        {
          x: 18,
          y: 27,
          w: 6,
          h: 15,
          data: 'ABQUAAAAFBQUFAAAFBQUFAAAFBQUFAAAFBQUFBQAABQUFBQUABQUFBQUABQUFBQUABQUFBQAABQUFBQAAAICFBQAAAACAgAAAAACAgAAAAACAgAAAAAAAgIA',
        },
        {
          x: 14,
          y: 30,
          w: 11,
          h: 8,
          data: 'AAAAFAAAAAAAAAAAAAAUAAAAAAAAAAAAABQAAAAAAAAAAAAAFAAAAAAAAAAAAAAAFAAAAAAAAAAAAgIAFAAAABQUAAICAgIUFBQUFAACAgICFBQUFBQUAA==',
        },
      ],
    },
    {
      name: 'torso',
      cels: [
        {
          x: 20,
          y: 20,
          w: 8,
          h: 9,
          data: 'AAANDQAAAAAADQ0AAAAAAAANDQAAAAANAA0NDQAADQYNDQ0NDQ0GBg0NDQ0NBgYGDQ0NDQYGBgANDQ0GBgYGAAAADQ0GBgAA',
        },
        {
          x: 22,
          y: 20,
          w: 8,
          h: 9,
          data: 'AA0AAAAAAAANDQAAAAAADQ0NAAAAAA0GDQ0NAAANBgAADQ0NDQ0GAAANDQ0NDQYAAA0NDQ0GBgAADQ0NBgYGAAAAAA0NBgYA',
        },
        {
          x: 16,
          y: 15,
          w: 9,
          h: 12,
          data: 'AAAABgYAAAAAAAAGBgAAAAAAAAYNAAAAAAAAAA0NAAAAAAAADQ0NDQAAAAAADQ0NDQ0AAAAADQ0NDQ0NDQAADQ0NDQ0NDQ0NAA0NDQ0NDQ0AAA0NDQ0NDQAAAAANDQ0NAAAAAAAADQAAAAAA',
        },
        {
          x: 17,
          y: 19,
          w: 10,
          h: 9,
          data: 'AAANAAAAAA0GBgANDQ0AAA0GBgANDQ0NDQ0GBgAADQ0NDQ0NBgAAAA0NDQ0NDQ0GAAANDQ0NDQ0NDQ0AAA0NDQ0NDQ0AAAANDQ0NDQ0AAAAADQAADQ0AAAAA',
        },
        {
          x: 17,
          y: 23,
          w: 9,
          h: 8,
          data: 'AAAAAAAADQ0AAAAAAA0NDQ0AAAAADQ0NDQ0NAAANDQ0NDQYAAA0NDQ0NBgAADQ0NDQ0GBgAADQ0NDQYGAAAAAA0AAAAAAAAA',
        },
      ],
    },
    {
      name: 'leg.near',
      cels: [
        {
          x: 19,
          y: 28,
          w: 8,
          h: 14,
          data: 'AAgIAAAAAAAICAgICAgIAAgICAgICAgAAAgICAgICAAAAAgICAgICAAAAAgICAgIAAAACAgICAAAAAgICAgIAAAACQgICAAAAAkJCQgAAAAACQkAAAAAAAAJCQAAAAAAAAkAAAAAAAAACQAAAAAAAA==',
        },
        {
          x: 23,
          y: 28,
          w: 8,
          h: 14,
          data: 'CAgAAAAAAAAICAgICAgAAAgICAgICAAACAgICAgIAAAACAgICAgIAAAACAgICAgAAAAACAgICAAAAAAICAgIAAAAAAgICAAAAAAACAgIAAAAAAAICAgAAAAAAAkJCQAAAAAAAAkJCQAAAAAAAAkJCQ==',
        },
        {
          x: 19,
          y: 22,
          w: 10,
          h: 12,
          data: 'AAAAAAAACAgIAAAAAAAACAgICAgAAAAACAgICAgIAAAACAgICAgICAAICAgICAgICAgICAgICAgICAgACAgICAgICAgIAAgICAgICAkICAAICAgICAAJCQgAAAgICAAACQkJAAAAAAAAAAkJCQAAAAAAAAAACQkJ',
        },
        {
          x: 22,
          y: 23,
          w: 12,
          h: 9,
          data: 'AAAAAAAICAgAAAAAAAAAAAgICAgIAAAAAAAACAgICAgIAAAAAAAICAgICAgICAAAAAgICAgICAgICAAACAgICAgICAgICAAACAgICAgICAkJCQAACAgICAgIAAkJCQkAAAgICAgAAAAJCQkJ',
        },
        {
          x: 18,
          y: 29,
          w: 13,
          h: 9,
          data: 'AAAAAAAAAAAICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAAACAgICAgIAAgICAgAAAAICAgAAAkICAgAAAAAAAAAAAkJCQkAAAAAAAAAAAAJCQkJCQAA',
        },
      ],
    },
    {
      name: 'arm.near',
      cels: [
        {
          x: 23,
          y: 11,
          w: 9,
          h: 13,
          data: 'AAAAAAAACwsAAAAAAAALCwsLAAAAAAALCwAAAAAAAAAKCgAAAAAAAAAKCgAAAAAAAAAKCgAAAAAAAAoKCgAAAAAACgoKCgAAAAAKCgoKAAAAAAoKCgoKAAAACgoKCgoAAAAACgoKCgAAAAAAAAoKAAAAAAAA',
        },
        {
          x: 24,
          y: 12,
          w: 8,
          h: 12,
          data: 'AAAAAAALCwAAAAAACwsLCwAAAAALCwAAAAAAAAoKAAAAAAAACgoAAAAAAAAKCgAAAAAACgoKAAAACgoKCgoAAAoKCgoKCgAACgoKCgoAAAAKCgoKAAAAAAAKCgAAAAAA',
        },
        {
          x: 19,
          y: 15,
          w: 12,
          h: 7,
          data: 'AAAAAAAAAAALCwAAAAoKAAAAAAsLCwsACgoKCgAAAAsLCwsLCgoKCgoACgsLAAAAAAoKCgoKCgoLAAAAAAAKCgoKCgoAAAAAAAAAAAoKCgAAAAAA',
        },
        { x: 24, y: 20, w: 5, h: 4, data: 'AAAKCgAACgoKCgoKCgoKAAoKAAA=' },
        {
          x: 23,
          y: 26,
          w: 11,
          h: 12,
          data: 'AAAKCgAAAAAAAAAACgoKCgAAAAAAAAAKCgoKAAAAAAAACgoKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAALAAAAAAAAAAAACwsLAAAAAAAAAAALCwsAAAAAAAAAAAALCwsL',
        },
      ],
    },
    {
      name: 'head',
      cels: [
        {
          x: 20,
          y: 12,
          w: 8,
          h: 8,
          data: 'AAAMDAwMAAAADAwMDAwMAAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwAAAwMDAwMAAAAAAwMDAAAAA==',
        },
        {
          x: 22,
          y: 13,
          w: 6,
          h: 7,
          data: 'AAAMDAwMAAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwAAAwMAAAA',
        },
        {
          x: 21,
          y: 11,
          w: 8,
          h: 8,
          data: 'AAAMDAwMAAAADAwMDAwMAAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwAAAAMDAwMAAAAAAAMDAwAAAAAAAAMAAAAAA==',
        },
        {
          x: 19,
          y: 15,
          w: 8,
          h: 6,
          data: 'AAAMDAwMAAAADAwMDAwMAAwMDAwMDAwMDAwMDAwMDAwADAwMDAAAAAAADAwAAAAA',
        },
        {
          x: 25,
          y: 19,
          w: 8,
          h: 8,
          data: 'AAAMDAwMAAAADAwMDAwMAAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAAwMDAwMDAAAAAwMDAwAAA==',
        },
      ],
    },
  ],
};
