// hana-run.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/run.aseprite (8 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_RUN: SpriteAnim = {
  name: "hana-run",
  w: 79,
  h: 79,
  frames: 8,
  ground: 40,
  durations: [100, 100, 100, 100, 100, 100, 100, 100],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 42, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 43, y: 32, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 39, y: 32, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhgYFxcWABYYGBcXFgA=' },
        { x: 35, y: 33, w: 8, h: 5, data: 'ABYYGBgYGBYAFhcXFxcXFgAWFxcXFxcWFhgYGBcXFxYWGBgWFhcXFg==' },
        { x: 36, y: 34, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhgYGBcXFgAAABYXFxY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYAFhgXFxgWABYYFxcWAA==' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXGBgWABYXFxgYFgA=' },
        { x: 35, y: 33, w: 8, h: 5, data: 'ABYYGBgYGBYAFhcXFxcXFgAWFxcXFxcWFhcXFxgYGBYWFxcWFhgYFg==' },
        { x: 36, y: 34, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgYFgAAABYYGBY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYAFhcXGBYAABYXFxgWAA==' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 23, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 24, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 23, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 24, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 33, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 32, y: 32, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 33, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 35, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 36, y: 32, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 35, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
  ],
};
