// hana-death.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/death.aseprite (6 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_DEATH: SpriteAnim = {
  name: "hana-death",
  w: 79,
  h: 79,
  frames: 6,
  ground: 40,
  durations: [100, 100, 100, 100, 100, 500],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 41, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 46, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 51, y: 37, w: 4, h: 3, data: 'ABYWABYXFxYWFxgW' },
        { x: 51, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 51, y: 37, w: 4, h: 3, data: 'ABYWABYXFxYWFxgW' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 34, y: 34, w: 9, h: 6, data: 'FhgYGBgWFgAAFhcXFxcXFgAAABYXFxcXFxYAABYXFxcXFxYAAAAWFxcYGBgWAAAWFxcWGBgW' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgWFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
        { x: 36, y: 35, w: 10, h: 5, data: 'AAAAFhgAAAAAAAAAFhcXGBgYGBYAFhcXFxcXFxYAFhcXFxcXFxYAABYXFxcYGBgWAAA=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'AAAAFhYWFgAAFhcXFxgWFhcXFxcYFhcXFxgYGA==' },
        { x: 36, y: 36, w: 7, h: 4, data: 'AAAAFhYWFgAAFhcXFxgWFhcXFxgYFhcXFxgWFg==' },
        { x: 36, y: 36, w: 7, h: 4, data: 'AAAAFhYWFgAAFhcXFxgWFhcXFxcYFhcXFxgYGA==' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 32, y: 24, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 38, y: 26, w: 11, h: 11, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWAAAAFxcXFxcXFgAAAAAAAAAAABYAAA==' },
        { x: 41, y: 30, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 41, y: 29, w: 11, h: 11, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgAAABYWFhYWFhYAAA==' },
        { x: 41, y: 30, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 34, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 36, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 37, w: 4, h: 3, data: 'ABYWABYXFxYWFxgW' },
        { x: 41, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 37, w: 4, h: 3, data: 'ABYWABYXFxYWFxgW' },
      ],
    },
  ],
};
