// hana-pick-up.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/pick up.aseprite (6 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_PICK_UP: SpriteAnim = {
  name: "hana-pick-up",
  w: 79,
  h: 79,
  frames: 6,
  ground: 40,
  durations: [100, 100, 100, 100, 100, 500],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 42, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 45, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 44, y: 32, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 43, y: 27, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 28, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 43, y: 29, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
        { x: 36, y: 36, w: 8, h: 4, data: 'ABYYGBgYGBYAFhcXFxcXFhYXFxcXGBgWFhcXFhYYGBY=' },
        { x: 35, y: 35, w: 9, h: 5, data: 'FhgYGBgYFgAAABYXFxcXFxYAABYXFxcXFxYAABYXFxcYGBgWABYXFxYWGBgW' },
        { x: 36, y: 35, w: 8, h: 5, data: 'FhgYGBgYFgAWFxcXFxcWABYXFxcXFxYAFhcXFxgYGBYWFxcWFhgYFg==' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 35, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 33, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcYFxcYFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcYFxcYFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 37, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 37, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 37, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 31, y: 27, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 31, y: 28, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 32, y: 29, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
  ],
};
