// hana-hurt.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/hurt.aseprite (4 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_HURT: SpriteAnim = {
  name: "hana-hurt",
  w: 79,
  h: 79,
  frames: 4,
  ground: 40,
  durations: [100, 100, 100, 100],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 41, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 34, y: 34, w: 9, h: 6, data: 'FhgYGBgWFgAAFhcXFxcXFgAAABYXFxcXFxYAABYXFxcXFxYAAAAWFxcYGBgWAAAWFxcWGBgW' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgWFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYWFxcXGBgWFhcXFhgYFg==' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYWFxcXGBgWFhcXFhgYFg==' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 32, y: 24, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxYWFxYWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 33, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
  ],
};
