// hana-walk.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/walk.aseprite (8 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_WALK: SpriteAnim = {
  name: "hana-walk",
  w: 79,
  h: 79,
  frames: 8,
  ground: 40,
  durations: [100, 100, 100, 100, 100, 100, 100, 100],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 42, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 40, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhgXFxcWABYYGBcXFgA=' },
        { x: 35, y: 36, w: 8, h: 4, data: 'ABYYGBgYGBYAFhcXFxcXFhYYGBgWFxcWFhgYFhYXFxY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYWGBgYFxcWFhgYFhcXFg==' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhgYFxcWAAAWGBcXFgA=' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgWABYXFxgYFgA=' },
        { x: 35, y: 36, w: 8, h: 4, data: 'ABYYGBgYGBYAFhcXFxcXFhYXFxcYGBgWFhcXFhYYGBY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYWFxcXGBgWFhcXFhgYFg==' },
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgWAAAWFxgYFgA=' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcXFhcXFhYWGBcXFxcWFxcWFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 33, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 33, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 33, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 35, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 35, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 35, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
  ],
};
