// hana-jump.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Source: Hana Caraka - Base Character/Basic/jump.aseprite (6 frames, 79x79)
//
// Pixels are indices into TEMPLATE_PALETTE (see ../palette.ts), never colours.
import type { SpriteAnim } from '../../sprite';

export const HANA_JUMP: SpriteAnim = {
  name: "hana-jump",
  w: 79,
  h: 79,
  frames: 6,
  ground: 40,
  durations: [100, 100, 100, 100, 100, 100],
  layers: [
    {
      name: "arm.far",
      cels: [
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 41, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 43, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 42, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
    {
      name: "torso",
      cels: [
        { x: 36, y: 35, w: 7, h: 5, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxgYFhYXFxYYGBY=' },
        { x: 36, y: 36, w: 7, h: 4, data: 'FhgYGBgYFhYXFxcXFxYWFxcXGBgWFhcXFhgYFg==' },
        { x: 36, y: 37, w: 7, h: 3, data: 'FhgYGBgYFhYXFxcYGBYWFxcWGBgW' },
        { x: 36, y: 34, w: 7, h: 6, data: 'FhgYGBgYFhYXFxcXFxYWFxcXFxcWFhcXFxcXFhYXFxcYGBYWFxcWGBgW' },
        { x: 35, y: 35, w: 9, h: 5, data: 'ABYYGBgYGBYAABYXFxcXFxYAABYXFxcXFxYAFhcXFxcYGBgWFhcXFhYWGBgW' },
        { x: 35, y: 35, w: 9, h: 5, data: 'ABYYGBgYGBYAABYXFxcXFxYAABYXFxcXFxYAFhcXFxcYGBgWFhcXFhYWGBgW' },
      ],
    },
    {
      name: "head",
      cels: [
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 26, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 27, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgYFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 24, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
        { x: 34, y: 25, w: 11, h: 10, data: 'AAAWFhYWFhYWAAAAFhgYFxcXFxcWABYYGBcXFxcXFxcWFhgXFxcXFxcXFxYWGBcXFxcXFxcXFhYYFxcXFxcXFxcWFhgXFxcWFxcWFxYWGBcXFxYXFxYXFhYYFxcXFxcXFxcWABYYFxcXFxcXFgA=' },
      ],
    },
    {
      name: "arm.near",
      cels: [
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 34, y: 36, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 32, y: 34, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
        { x: 33, y: 35, w: 4, h: 4, data: 'ABYWABYXFxYWFxgWABYWAA==' },
      ],
    },
  ],
};
