// index.ts — GENERATED by tools/import-aseprite.ts. Do not edit by hand.
//
// Every hana animation listed in tools/sprite-manifest.ts. The source animations
// deliberately NOT imported, and why, are recorded there too.
import { HANA_IDLE } from './hana-idle';
import { HANA_WALK } from './hana-walk';
import { HANA_RUN } from './hana-run';
import { HANA_JUMP } from './hana-jump';
import { HANA_HURT } from './hana-hurt';
import { HANA_DEATH } from './hana-death';
import { HANA_PICK_UP } from './hana-pick-up';

export const HANA_SPRITES = {
  idle: HANA_IDLE,
  walk: HANA_WALK,
  run: HANA_RUN,
  jump: HANA_JUMP,
  hurt: HANA_HURT,
  death: HANA_DEATH,
  pick_up: HANA_PICK_UP,
} as const;

export type HanaAnim = keyof typeof HANA_SPRITES;

/**
 * The layer slots a hana animation may use, in paint order.
 *
 * Normalised at import precisely so a skin or material authored once applies to every animation —
 * the source pack calls the same body part by several different names across its files.
 */
export const HANA_SLOTS = ['arm.far', 'torso', 'head', 'arm.near'] as const;

export type HanaSlot = (typeof HANA_SLOTS)[number];
