// constants.ts — the WGSL prelude of tuning constants, GENERATED from the TypeScript that owns them.
//
// The shaders are ports of cave-render.ts and lighting.ts, and those files are where every one of these
// numbers is tuned. Writing them into the .wgsl files by hand would give each a second home, and the
// first retune would split the CPU and GPU looks apart without anything noticing. So the shaders
// reference names, and this module emits `const` declarations for them from the live values.
import { T, TEX } from '../palette';
import {
  DIAGONAL,
  EDGE_EROSION_BASE,
  EDGE_EROSION_RANGE,
  EDGE_NOISE_FREQ,
  CORNER_ROUND_BASE,
  CORNER_ROUND_NOISE,
  CONTACT_SHADOW_NEAR,
  CONTACT_SHADOW_FAR,
  SHADE_RANGE_TOP_PX,
  SHADE_RANGE_SIDE_PX,
  TOP_LIGHT_ROWS,
  BG_SILHOUETTE_FREQ_X,
  BG_SILHOUETTE_FREQ_Y,
  BG_SILHOUETTE_THRESHOLD,
  FEATHER_FREQ,
  BLEND_WIDTH,
} from '../cave-render';
import {
  DITHER_STEPS,
  SCRIM,
  LIGHT_FLOOR,
  MAX_DARKNESS,
  VIGNETTE_INNER,
  VIGNETTE_SPAN,
  VIGNETTE_MAX,
  OPEN_ATTEN,
  ROCK_ATTEN,
  DIAGONAL_ATTEN,
  ADD,
  ADD_MAX,
  GLOW_CAP,
  SEED_FLOATS,
} from '../lighting';

/** A float literal WGSL accepts: always with a decimal point, so `2` doesn't become an integer. */
const float = (value: number): string =>
  Number.isInteger(value) ? value.toFixed(1) : String(value);

const declarations: readonly string[] = [
  `const T: i32 = ${T};`,
  `const TEX: u32 = ${TEX}u;`,
  `const DIAGONAL: f32 = ${float(DIAGONAL)};`,
  `const EDGE_EROSION_BASE: f32 = ${float(EDGE_EROSION_BASE)};`,
  `const EDGE_EROSION_RANGE: f32 = ${float(EDGE_EROSION_RANGE)};`,
  `const EDGE_NOISE_FREQ: f32 = ${float(EDGE_NOISE_FREQ)};`,
  `const CORNER_ROUND_BASE: f32 = ${float(CORNER_ROUND_BASE)};`,
  `const CORNER_ROUND_NOISE: f32 = ${float(CORNER_ROUND_NOISE)};`,
  `const CONTACT_SHADOW_NEAR: f32 = ${float(CONTACT_SHADOW_NEAR)};`,
  `const CONTACT_SHADOW_FAR: f32 = ${float(CONTACT_SHADOW_FAR)};`,
  `const SHADE_RANGE_TOP_PX: f32 = ${float(SHADE_RANGE_TOP_PX)};`,
  `const SHADE_RANGE_SIDE_PX: f32 = ${float(SHADE_RANGE_SIDE_PX)};`,
  `const TOP_LIGHT_ROWS: i32 = ${TOP_LIGHT_ROWS};`,
  `const BG_SILHOUETTE_FREQ_X: f32 = ${float(BG_SILHOUETTE_FREQ_X)};`,
  `const BG_SILHOUETTE_FREQ_Y: f32 = ${float(BG_SILHOUETTE_FREQ_Y)};`,
  `const BG_SILHOUETTE_THRESHOLD: f32 = ${float(BG_SILHOUETTE_THRESHOLD)};`,
  `const FEATHER_FREQ: f32 = ${float(FEATHER_FREQ)};`,
  `const BLEND_WIDTH: f32 = ${float(BLEND_WIDTH)};`,
  `const DITHER_STEPS: i32 = ${DITHER_STEPS};`,
  `const SCRIM = vec3f(${SCRIM.map(float).join(', ')});`,
  `const LIGHT_FLOOR: f32 = ${float(LIGHT_FLOOR)};`,
  `const MAX_DARKNESS: f32 = ${float(MAX_DARKNESS)};`,
  `const VIGNETTE_INNER: f32 = ${float(VIGNETTE_INNER)};`,
  `const VIGNETTE_SPAN: f32 = ${float(VIGNETTE_SPAN)};`,
  `const VIGNETTE_MAX: f32 = ${float(VIGNETTE_MAX)};`,
  `const OPEN_ATTEN: f32 = ${float(OPEN_ATTEN)};`,
  `const ROCK_ATTEN: f32 = ${float(ROCK_ATTEN)};`,
  `const DIAGONAL_ATTEN: f32 = ${float(DIAGONAL_ATTEN)};`,
  `const ADD: f32 = ${float(ADD)};`,
  `const ADD_MAX: f32 = ${float(ADD_MAX)};`,
  `const GLOW_CAP: f32 = ${float(GLOW_CAP)};`,
  `const SEED_FLOATS: u32 = ${SEED_FLOATS}u;`,
];

export const CONSTANTS_WGSL = `// generated by gpu/constants.ts — edit the TypeScript, not this\n${declarations.join('\n')}\n`;
