// materials.ts — the WGSL for every registered material (#73), GENERATED from the material registry.
//
// A material's colours have one home, its TypeScript registration (materials/<name>.ts): the palette
// ramp and the named accents. This emits them as WGSL constants its twin shader reads — <NAME>_BANDS
// (the six quantiser bands, dark → light, exactly as palette.ts's stone bands order them), <NAME>_RIM_B,
// <NAME>_RIM_ROCK and <NAME>_<ACCENT> — then every twin's source, then the two things the compositor
// needs: the dispatch from a material id to its shader, and each material's feather. See
// docs/MATERIALS.md, "GPU twins".
import { colorsFor, hexRgb } from '../palette';
import type { RockColors } from '../palette';
import { DEFAULT_FEATHER } from '../cave-render';
import { allOreMaterials } from '../materials';

/** The largest material id the packed world cell has room for (8 bits; see world-window.ts). */
const MAX_MATERIAL_ID = 255;

const float = (value: number): string =>
  Number.isInteger(value) ? value.toFixed(1) : String(value);
const vec3 = (rgb: readonly number[]): string => `vec3f(${rgb.map(float).join(', ')})`;

/** palette.ts's stone bands, dark → light: the order `quantize` walks and every surface indexes. */
const bandsOf = (colours: RockColors): string =>
  `array<vec3f, 6>(${[
    colours.center,
    colours.deep,
    colours.body,
    colours.body2,
    colours.lit,
    colours.rimA,
  ]
    .map(vec3)
    .join(', ')})`;

export function materialsWgsl(): string {
  const materials = allOreMaterials();
  const declarations: string[] = [];
  const cases: string[] = [];
  let featherTableSize = 1;
  for (const [id, material] of materials) {
    if (id < 1 || id > MAX_MATERIAL_ID)
      throw new Error(`material id ${id} doesn't fit a packed cell`);
    const prefix = material.name.toUpperCase();
    const colours = colorsFor([...material.palette]);
    declarations.push(
      `const ${prefix}_BANDS = ${bandsOf(colours)};`,
      `const ${prefix}_RIM_B = ${vec3(colours.rimB)};`,
      `const ${prefix}_RIM_ROCK = ${vec3(colours.rimRock)};`,
      ...Object.entries(material.accents ?? {}).map(
        ([key, hex]) => `const ${prefix}_${key.toUpperCase()} = ${vec3(hexRgb(hex))};`,
      ),
    );
    cases.push(`    case ${id}u: { return shade_${material.name}(ctx); }`);
    featherTableSize = Math.max(featherTableSize, id + 1);
  }
  const feathers = Array.from({ length: featherTableSize }, () => DEFAULT_FEATHER);
  for (const [id, material] of materials) feathers[id] = material.feather ?? DEFAULT_FEATHER;

  return [
    '// generated by gpu/materials.ts from the material registry — edit the materials, not this',
    ...declarations,
    ...materials.map(([, material]) => material.wgsl),
    `const MATERIAL_FEATHER = array<f32, ${featherTableSize}>(${feathers.map(float).join(', ')});`,
    `fn material_feather(id: u32) -> f32 {`,
    `  if (id >= ${featherTableSize}u) { return ${float(DEFAULT_FEATHER)}; }`,
    `  return MATERIAL_FEATHER[id];`,
    `}`,
    `// A registered material's shader, or false for id 0 and anything unregistered (plain stone).`,
    `fn has_material(id: u32) -> bool {`,
    `  switch id {`,
    `    case ${materials.map(([id]) => `${id}u`).join(', ')}: { return true; }`,
    `    default: { return false; }`,
    `  }`,
    `}`,
    `fn material_shade(id: u32, ctx: ShadeCtx) -> vec3f {`,
    `  switch id {`,
    ...cases,
    `    default: { return vec3f(0.0); }`,
    `  }`,
    `}`,
    '',
  ].join('\n');
}
