#!/bin/bash
# fetch.sh — fetch Terraria 1.4.0.5's decompiled sources the oracle compiles (Re-Logic's code: .gitignored, never
# committed) and extract the Smooth World pass from WorldGen.cs into SmoothWorld.generated.cs. Needs `gh`.
set -euo pipefail
cd "$(dirname "$0")"
fetch() { gh api "repos/AliceSavard/Terarria1405/contents/$1" --jq .download_url | xargs curl -sfL -o "$2"; }
fetch Liquid.cs Liquid.cs
fetch LiquidBuffer.cs LiquidBuffer.cs
fetch GameContent/Liquid/LiquidRenderer.cs LiquidRenderer.cs
fetch WorldGen.cs WorldGen.cs.txt
# the body of the "Smooth World" generation pass: from the line after its opening brace to the line before `}));`
start=$(grep -n 'AddGenerationPass("Smooth World"' WorldGen.cs.txt | cut -d: -f1)
end=$(awk -v s="$start" 'NR > s && /^      }\)\);/ { print NR; exit }' WorldGen.cs.txt)
{
  echo '// Generated by fetch.sh from WorldGen.cs (Terraria 1.4.0.5, decompiled): the "Smooth World" pass, unmodified.'
  echo 'using Terraria.ID;'
  echo 'namespace Terraria { public static class SmoothWorldPass { public static void Run(ProgressStub progress, object passConfig) {'
  sed -n "$((start + 2)),$((end - 1))p" WorldGen.cs.txt
  echo '} } }'
} > SmoothWorld.generated.cs
rm WorldGen.cs.txt
echo "extracted WorldGen.cs lines $((start + 2))–$((end - 1))"
# the player's collision routines from Collision.cs: each method from its signature to its closing brace
fetch Collision.cs Collision.cs.txt
{
  echo '// Generated by fetch.sh from Collision.cs (Terraria 1.4.0.5, decompiled): the player collision methods, unmodified.'
  echo 'using System; using Microsoft.Xna.Framework; using Terraria.ID;'
  echo 'namespace Terraria { public static class Collision {'
  echo '    public static bool stair, stairFall, sloping, up, down;'
  for method in WalkDownSlope SlopeCollision TileCollision StepDown StepUp; do
    start=$(grep -n "^    public static [A-Za-z0-9]* $method($" Collision.cs.txt | cut -d: -f1)
    end=$(awk -v s="$start" 'NR > s && /^    }$/ { print NR; exit }' Collision.cs.txt)
    sed -n "${start},${end}p" Collision.cs.txt
    echo "extracted $method: Collision.cs lines ${start}–${end}" >&2
  done
  echo '} }'
} > Collision.generated.cs
rm Collision.cs.txt
